name: 发布到 npm
on:
  push:
    branches: [main]

jobs:
  pub:
    name: |
      发布到 npm
      仅在提交的代码包含 `version` 字样时才运行该动作
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    if: contains(github.event.head_commit.message, 'version')
    steps:
      - name: 代码检出
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: 初始化 Node 并设定 Node 版本
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: 安装 dependencies 依赖
        run: |
          npm ci

      - name: 构建
        run: |
          npm run build

      - name: 发布到 npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd dist
          npm publish --provenance --access public
